### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by bkauler** [cfenollosa/bashblog#138]
Hi guys,
I tried bashblog for the first time yesterday, like it!

My understanding from reading the docs, is that bb.sh is intended to be run on the remote host site. Yeah, I tried that, but decided I would prefer to develop locally, including offline.

I made some simple changes. Let me know if I have misunderstood anything, or if you can see a problem with this setup.

On my PC, I placed 'bb.sh' and 'Markdown.pl' in a folder, and created 'config', a script 'remote-rsync' and a folder 'LOCAL'.

Just made a couple of changes to bb.sh:

Inserted at line 8:

`cd LOCAL`

Edited these two lines:

```
global_config="../config"
[[ -f ../Markdown.pl ]] && markdown_bin=../Markdown.pl || markdown_bin=$(which Markdown.pl 2>/dev/null || which markdown 2>/dev/null)
```

Just run:
`> ./bb.sh <params>`

It seems to work OK.

Whenever I want to upload, execute:
`> ./remote-sync`

Which is a simple one-liner:

```
#!/bin/bash
#upload LOCAL contents to remote site

# -r recursive -t preserve modification time -z compress
# -v verbose   -l copy symlinks as symlinks  -u delta-transfer
# -e execute   -c checksum comparison
rsync --delete -rltzvuc -e "ssh -p 22" LOCAL/ username@host:path/
```

Make substitutions for username, host and path to suit your host.

Regards,
Barry Kauler

**Comment by JohnDarkhorse** [comment]
Instead of editing the bb.sh directly, IMHO  you should create a file containing lines 11 through 143 of https://github.com/cfenollosa/bashblog/blob/master/bb.sh.  Name it .config and put it in the folder where you write your blog.

Otherwise, your changes to bb.sh may be nuked if you update via git.

Using the separate .config file also allows you to run the bb.sh in multiple folders ( with multiple .config files ).  I am using bb.sh to make several different sorts of blog, all using different .config and css files
