### ISSUE TITLE
[ Suggestion ] Invoke an URL shortener for Twitter

### ISSUE THREAD

**Issue by i90rr** [cfenollosa/bashblog#84]
I could try to implement this feature :)

**Comment by cfenollosa** [comment]
I appreciate the effort, but I'm afraid this is probably not a suitable feature for bashblog. Please read the [Contributing](https://github.com/cfenollosa/bashblog#contributing) section of the HOWTO for a more detailed explanation

I'm really sorry to reject features and understand that this can be a bit of a let down, but I'd rather be honest up front, before you even start coding, and then reject a patch. I hope you understand.

Due to some changes around the Twitter search policy and other search engines closing, I'll probably rewrite the Twitter module to eliminate clutter.

**Comment by i90rr** [comment]
Yeah, I'm aware of the minimalist approach and the goal of keeping bashblog as small and tidy as possible; my suggestion came after I saw some posts could have a really big URI, leaving little space for the twit description.
Cheers.

**Comment by cfenollosa** [comment]
Twitter already shortens the URL internally. Try it: Start a twit, write "hello world http://example.com". 105 chars remaining. Then change the URL to http://example.com/longerurl. Same 105 characters remaining :)
